"use client";

import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-950 text-gray-800 dark:text-gray-200 transition-colors duration-300">
      <div className="max-w-4xl mx-auto px-6 py-12">
        {/* Header */}
        <div className="mb-8">
          <Link href="/" className="inline-flex items-center gap-2 text-purple-600 hover:text-purple-700 font-medium mb-6 transition-colors">
            <ArrowLeft size={20} />
            Back to Home
          </Link>
          <h1 className="text-3xl md:text-4xl font-bold mb-2 text-gray-900 dark:text-white">Terms of Service</h1>
          <p className="text-gray-500 dark:text-gray-400">Last Updated: January 2026</p>
        </div>

        {/* Content */}
        <div className="prose dark:prose-invert max-w-none space-y-8 bg-white dark:bg-gray-900 p-8 rounded-2xl shadow-sm border border-gray-100 dark:border-gray-800">
          
          <section>
            <h2 className="text-xl font-bold mb-3 text-gray-900 dark:text-gray-100">1. Acceptance of Terms</h2>
            <p className="leading-relaxed">
              By accessing or using CareerSathi ("the Service"), you agree to be bound by these Terms of Service. If you disagree with any part of the terms, you may not access the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3 text-gray-900 dark:text-gray-100">2. Description of Service</h2>
            <p className="leading-relaxed">
              CareerSathi provides an AI-powered chat interface designed to offer career guidance, resume reviews, and interview preparation tips.
            </p>
          </section>

          <section className="bg-amber-50 dark:bg-amber-900/20 border-l-4 border-amber-500 p-4 rounded-r-lg">
            <h2 className="text-xl font-bold mb-2 text-amber-800 dark:text-amber-200">3. AI Disclaimer (Important)</h2>
            <p className="leading-relaxed text-amber-900 dark:text-amber-100 font-medium">
              The advice, roadmaps, and content generated by CareerSathi are created by Artificial Intelligence. While we strive for accuracy, AI can hallucinate or provide outdated information.
            </p>
            <ul className="list-disc pl-5 space-y-2 mt-2 text-amber-900 dark:text-amber-100">
              <li>This service is for <strong>informational purposes only</strong>.</li>
              <li>It does <strong>not</strong> constitute professional legal, financial, or certified career counseling.</li>
              <li>You should always verify important career decisions with human professionals or official sources.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3 text-gray-900 dark:text-gray-100">4. User Accounts (Google Login)</h2>
            <p className="leading-relaxed">
              To access certain features, you must log in via your Google Account. You are responsible for maintaining the confidentiality of your account access and for all activities that occur under your account.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3 text-gray-900 dark:text-gray-100">5. User Conduct</h2>
            <p className="leading-relaxed">You agree not to:</p>
            <ul className="list-disc pl-5 space-y-2 leading-relaxed mt-2">
              <li>Use the Service for any illegal purpose.</li>
              <li>Attempt to "jailbreak" or trick the AI into generating harmful, hateful, or explicit content.</li>
              <li>Harass, abuse, or harm another person through the use of the Service.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3 text-gray-900 dark:text-gray-100">6. Limitation of Liability</h2>
            <p className="leading-relaxed">
              In no event shall CareerSathi, nor its developers, be liable for any indirect, incidental, special, or consequential damages arising out of your use of the Service or reliance on any information provided by the AI.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3 text-gray-900 dark:text-gray-100">7. Changes to Terms</h2>
            <p className="leading-relaxed">
              We reserve the right to modify or replace these Terms at any time. Your continued use of the Service after any such changes constitutes your acceptance of the new Terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3 text-gray-900 dark:text-gray-100">8. Contact Us</h2>
            <p className="leading-relaxed">
              If you have any questions about these Terms, please contact us at: <a href="mailto:support@zelphine.com" className="text-blue-600 hover:underline">support@zelphine.com</a>
            </p>
          </section>

        </div>
      </div>
    </div>
  );
}